GET http://localhost:5000/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM1OTY0NTk3LCJleHAiOjE3Mzg1NTY1OTd9.8HEYK70rv7RAwmoPqqia36vUaMz8cRZqkN5HUGWF0X4
Content-Type: application/json

{
    "title": "Rust",
    "content": "Rust is a good programming language. Though I dislike the community."
}


# {
    
#     "email": "prasoon@gmail.com",
#     "password": "password123"
# }
